name: Destroy Terraform Infrastructure

on:
  workflow_dispatch:  # Allows manual triggering via GitHub Actions UI

jobs:
  destroy:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.10.4  # Specify the correct Terraform version

    - name: Terraform Init
      run: terraform init -input=false -backend-config="bucket=s3-bucket-terraform-1" -backend-config="key=env:${{ env.TF_ENV }}/Terraform/terraform.tfstate" -backend-config="region=eu-west-1"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        TF_ENV: dev  # Replace 'dev' with your workspace/environment variable if needed

    - name: Terraform Destroy
      run: terraform destroy -auto-approve
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}